In [17]:
import pandas as pd

In [ ]:
# testing!

In [24]:
candidate_data = pd.read_csv("./Resources/002_CleanData_CandidateSummaryAction.csv") 
candidate_data.head()

,Unnamed: 0,can_id,can_nam,can_off,can_off_sta,can_off_dis,can_par_aff,can_inc_cha_ope_sea,can_str1,can_str2,...,cas_on_han_beg_of_per,cas_on_han_clo_of_per,net_con,net_ope_exp,deb_owe_by_com,deb_owe_to_com,cov_sta_dat,cov_end_dat,winner,votes
0,0,H2GA12121,"ALLEN, RICHARD W",H,GA,12.0,REP,INCUMBENT,2237 PICKENS RD,NaN,...,60109.57,175613.35,1074949.50,907156.21,1125000.00,NaN,1/1/2015,10/19/2016,Y,158708.0
1,1,H6PA02171,"EVANS, DWIGHT",H,PA,2.0,DEM,CHALLENGER,PO BOX 6578,NaN,...,NaN,105687.23,1406719.06,1298831.83,NaN,NaN,11/2/2015,10/19/2016,Y,310770.0
2,2,H6FL04105,"RUTHERFORD, JOHN",H,FL,4.0,REP,OPEN,3817 VICKERS LAKE DRIVE,NaN,...,NaN,35645.09,650855.38,656210.29,60000.00,NaN,4/1/2016,10/19/2016,Y,286018.0
3,3,H4MT01041,"ZINKE, RYAN K",H,MT,0.0,REP,INCUMBENT,409 2ND ST W,NaN,...,83815.78,399122.61,4938943.74,5055942.15,NaN,NaN,1/1/2015,10/19/2016,Y,280476.0
4,4,H8CA09060,"LEE, BARBARA",H,CA,13.0,DEM,INCUMBENT,"409 13TH ST, 17TH FL",NaN,...,83690.60,181338.23,1197676.61,949488.98,4401.75,NaN,1/1/2015,10/19/2016,Y,277390.0

In [25]:
data_details = pd.read_csv("./Resources/DataDetails.csv") 
data_details.head()

,Tag,Field Name,Data Type,Description,Range,Explanation
0,lin_ima,Link to list of reports for the committee,URI,List of all disclosure filings for this committee,NaN,Link to list of filings made directly by the c...
1,can_id,Candidate Id,Character,NaN,9 characters,First character indicates office sought - H=Ho...
2,can_nam,Candidate Name,Character,Name of candidate,Max 90 characters,NaN
3,can_off,Candidate Office,Text,office abbreviation,1 character,P=President; S=Senate; H=House
4,can_off_sta,Candidate Office State,Character,Postal abbreviation for state,2 characters,NaN

In [26]:
columns = {}
detail_it = data_details.iterrows()
print(next(detail_it))

for row in detail_it:
    oldName = row[1][0]
    newName = row[1][1]
    columns[oldName] = newName

print(columns)

(0, Tag                                                      lin_ima
Field Name             Link to list of reports for the committee
Data Type                                                    URI
Description    List of all disclosure filings for this committee
Range                                                        NaN
Explanation    Link to list of filings made directly by the c...
Name: 0, dtype: object)
{'can_id': 'Candidate Id', 'can_nam': 'Candidate Name', 'can_off': 'Candidate Office', 'can_off_sta': 'Candidate Office State', 'can_off_dis': 'Candidate Office District', 'can_par_aff': 'Candidate Party Affiliation', nan: nan, 'can_inc_cha_ope_sea': 'Candidate Incumbent Challenger Open Seat', 'can_str1': 'Candidate Street 1', 'can_str2': 'Candidate Street 2', 'can_cit': 'Candidate City', 'can_sta': 'Candidate State', 'can_zip': 'Candidate Zip', 'ind_ite_con': 'Individual Itemized Contribution', 'ind_uni_con': 'Individual Unitemized Contribution', 'ind_con': 'Individual Contribution', 'par_com_con': 'Party Committee Contribution', 'oth_com_con': 'Other Committee Contribution', 'can_con': 'Candidate Contribution', 'tot_con': 'Total Contribution', 'tra_fro_oth_aut_com': 'Transfer from other Authorized Committee', 'can_loa': 'Candidate Loan', 'oth_loa': 'Other Loan', 'tot_loa': 'Total Loan', 'off_to_ope_exp': 'Offsets to Operating Expenditure', 'off_to_fun': 'Offsets to Fundraising', 'off_to_leg_acc': 'Offsets to Legal Accounting', 'oth_rec': 'Other Receipts', 'tot_rec': 'Total Receipts', 'ope_exp': 'Operating Expenditure', 'exe_leg_acc_dis': 'Exempt Legal Accounting Disbursement', 'fun_dis': 'Fundraising Disbursement', 'tra_to_oth_aut_com': 'Transfer to Other Authorized Committee', 'can_loa_rep': 'Candidate Loan Repayment', 'oth_loa_rep': 'Other Loan Repayment', 'tot_loa_rep': 'Total Loan Repayment', 'ind_ref': 'Individual Refund', 'par_com_ref': 'Party Committee Refund', 'oth_com_ref': 'Other Committee Refund', 'tot_con_ref': 'Total Contribution Refund', 'oth_dis': 'Other Disbursement', 'tot_dis': 'Total Disbursement', 'cas_on_han_beg_of_per': 'Cash on Hand Beginning of Period', 'cas_on_han_clo_of_per': 'Cash on Hand Close of Period', 'net_con': 'Net Contribution', 'net_ope_exp': 'Net Operating Expenditure', 'deb_owe_by_com': 'Debt Owed by Committee', 'deb_owe_to_com': 'Debt Owed to Committee', 'cov_sta_dat': 'Coverage Start Date', 'cov_end_dat': 'Coverage End Date'}

In [27]:
col = {}
col["Tag"] = "Field Name"

print(columns)

updated_can_data = candidate_data.rename(index=str, columns=columns)

updated_can_data.head()

{'can_id': 'Candidate Id', 'can_nam': 'Candidate Name', 'can_off': 'Candidate Office', 'can_off_sta': 'Candidate Office State', 'can_off_dis': 'Candidate Office District', 'can_par_aff': 'Candidate Party Affiliation', nan: nan, 'can_inc_cha_ope_sea': 'Candidate Incumbent Challenger Open Seat', 'can_str1': 'Candidate Street 1', 'can_str2': 'Candidate Street 2', 'can_cit': 'Candidate City', 'can_sta': 'Candidate State', 'can_zip': 'Candidate Zip', 'ind_ite_con': 'Individual Itemized Contribution', 'ind_uni_con': 'Individual Unitemized Contribution', 'ind_con': 'Individual Contribution', 'par_com_con': 'Party Committee Contribution', 'oth_com_con': 'Other Committee Contribution', 'can_con': 'Candidate Contribution', 'tot_con': 'Total Contribution', 'tra_fro_oth_aut_com': 'Transfer from other Authorized Committee', 'can_loa': 'Candidate Loan', 'oth_loa': 'Other Loan', 'tot_loa': 'Total Loan', 'off_to_ope_exp': 'Offsets to Operating Expenditure', 'off_to_fun': 'Offsets to Fundraising', 'off_to_leg_acc': 'Offsets to Legal Accounting', 'oth_rec': 'Other Receipts', 'tot_rec': 'Total Receipts', 'ope_exp': 'Operating Expenditure', 'exe_leg_acc_dis': 'Exempt Legal Accounting Disbursement', 'fun_dis': 'Fundraising Disbursement', 'tra_to_oth_aut_com': 'Transfer to Other Authorized Committee', 'can_loa_rep': 'Candidate Loan Repayment', 'oth_loa_rep': 'Other Loan Repayment', 'tot_loa_rep': 'Total Loan Repayment', 'ind_ref': 'Individual Refund', 'par_com_ref': 'Party Committee Refund', 'oth_com_ref': 'Other Committee Refund', 'tot_con_ref': 'Total Contribution Refund', 'oth_dis': 'Other Disbursement', 'tot_dis': 'Total Disbursement', 'cas_on_han_beg_of_per': 'Cash on Hand Beginning of Period', 'cas_on_han_clo_of_per': 'Cash on Hand Close of Period', 'net_con': 'Net Contribution', 'net_ope_exp': 'Net Operating Expenditure', 'deb_owe_by_com': 'Debt Owed by Committee', 'deb_owe_to_com': 'Debt Owed to Committee', 'cov_sta_dat': 'Coverage Start Date', 'cov_end_dat': 'Coverage End Date'}

,Unnamed: 0,Candidate Id,Candidate Name,Candidate Office,Candidate Office State,Candidate Office District,Candidate Party Affiliation,Candidate Incumbent Challenger Open Seat,Candidate Street 1,Candidate Street 2,...,Cash on Hand Beginning of Period,Cash on Hand Close of Period,Net Contribution,Net Operating Expenditure,Debt Owed by Committee,Debt Owed to Committee,Coverage Start Date,Coverage End Date,winner,votes
0,0,H2GA12121,"ALLEN, RICHARD W",H,GA,12.0,REP,INCUMBENT,2237 PICKENS RD,NaN,...,60109.57,175613.35,1074949.50,907156.21,1125000.00,NaN,1/1/2015,10/19/2016,Y,158708.0
1,1,H6PA02171,"EVANS, DWIGHT",H,PA,2.0,DEM,CHALLENGER,PO BOX 6578,NaN,...,NaN,105687.23,1406719.06,1298831.83,NaN,NaN,11/2/2015,10/19/2016,Y,310770.0
2,2,H6FL04105,"RUTHERFORD, JOHN",H,FL,4.0,REP,OPEN,3817 VICKERS LAKE DRIVE,NaN,...,NaN,35645.09,650855.38,656210.29,60000.00,NaN,4/1/2016,10/19/2016,Y,286018.0
3,3,H4MT01041,"ZINKE, RYAN K",H,MT,0.0,REP,INCUMBENT,409 2ND ST W,NaN,...,83815.78,399122.61,4938943.74,5055942.15,NaN,NaN,1/1/2015,10/19/2016,Y,280476.0
4,4,H8CA09060,"LEE, BARBARA",H,CA,13.0,DEM,INCUMBENT,"409 13TH ST, 17TH FL",NaN,...,83690.60,181338.23,1197676.61,949488.98,4401.75,NaN,1/1/2015,10/19/2016,Y,277390.0

In [31]:
updated_can_data['winner'] = updated_can_data['winner'].fillna(value="N")
updated_can_data

,Unnamed: 0,Candidate Id,Candidate Name,Candidate Office,Candidate Office State,Candidate Office District,Candidate Party Affiliation,Candidate Incumbent Challenger Open Seat,Candidate Street 1,Candidate Street 2,...,Cash on Hand Beginning of Period,Cash on Hand Close of Period,Net Contribution,Net Operating Expenditure,Debt Owed by Committee,Debt Owed to Committee,Coverage Start Date,Coverage End Date,winner,votes
0,0,H2GA12121,"ALLEN, RICHARD W",H,GA,12.0,REP,INCUMBENT,2237 PICKENS RD,NaN,...,60109.57,175613.35,1074949.50,907156.21,1125000.00,NaN,1/1/2015,10/19/2016,N,158708.0
1,1,H6PA02171,"EVANS, DWIGHT",H,PA,2.0,DEM,CHALLENGER,PO BOX 6578,NaN,...,NaN,105687.23,1406719.06,1298831.83,NaN,NaN,11/2/2015,10/19/2016,N,310770.0
2,2,H6FL04105,"RUTHERFORD, JOHN",H,FL,4.0,REP,OPEN,3817 VICKERS LAKE DRIVE,NaN,...,NaN,35645.09,650855.38,656210.29,60000.00,NaN,4/1/2016,10/19/2016,N,286018.0
3,3,H4MT01041,"ZINKE, RYAN K",H,MT,0.0,REP,INCUMBENT,409 2ND ST W,NaN,...,83815.78,399122.61,4938943.74,5055942.15,NaN,NaN,1/1/2015,10/19/2016,N,280476.0
4,4,H8CA09060,"LEE, BARBARA",H,CA,13.0,DEM,INCUMBENT,"409 13TH ST, 17TH FL",NaN,...,83690.60,181338.23,1197676.61,949488.98,4401.75,NaN,1/1/2015,10/19/2016,N,277390.0
5,5,H6NC04037,"PRICE, DAVID E.",H,NC,4.0,DEM,INCUMBENT,P. O. BOX 1986,NaN,...,216409.21,274287.84,725854.52,430826.04,NaN,NaN,1/1/2015,10/19/2016,N,275501.0
6,6,H2WI02124,"POCAN, MARK",H,WI,2.0,DEM,INCUMBENT,PO BOX 327,NaN,...,187549.87,412220.80,970385.04,445438.15,NaN,NaN,1/1/2015,10/19/2016,N,273520.0
7,7,H2MA09072,"LYNCH, STEPHEN",H,MA,8.0,DEM,INCUMBENT,105 FARRAGUT RD,NaN,...,406586.74,1010654.62,1092218.56,459790.68,NaN,1750.0,1/1/2015,10/19/2016,N,267944.0
8,8,H6OR02116,"WALDEN, GREGORY P MR.",H,OR,2.0,REP,INCUMBENT,1504 SHERMAN AVENUE,NaN,...,997259.73,1264468.82,3004650.64,1911215.54,NaN,NaN,1/1/2015,10/19/2016,N,267179.0
9,9,H2MA04073,"KENNEDY, JOSEPH P III",H,MA,4.0,DEM,INCUMBENT,PO BOX 590464,NaN,...,1400008.58,2858165.71,2784362.26,1537844.39,NaN,NaN,1/1/2015,10/19/2016,N,261356.0
10,10,H8WI09050,"SENSENBRENNER, F. JAMES JR.",H,WI,5.0,REP,INCUMBENT,N76 W14726 NORTH POINT DR.,NaN,...,393925.71,489657.75,365203.15,265824.16,NaN,NaN,1/1/2015,10/19/2016,N,260705.0
11,11,H0FL08208,"WEBSTER, DANIEL",H,FL,11.0,REP,INCUMBENT,P. O. BOX 1007,NaN,...,162472.14,76985.57,830657.86,785298.58,NaN,NaN,1/1/2015,10/19/2016,N,257881.0
12,12,H8ME01120,"PINGREE, CHELLIE M",H,ME,1.0,DEM,INCUMBENT,138 TURNER FARM RD,NaN,...,215458.53,546889.99,571307.98,238294.57,20000.00,NaN,1/1/2015,10/19/2016,N,255428.0
13,13,H6FL01119,"GAETZ, MATT",H,FL,1.0,REP,OPEN,"301 BROOKS STREET, SE",NaN,...,NaN,45404.66,951163.89,993759.23,120000.00,NaN,1/1/2016,10/19/2016,N,254280.0
14,14,H6FL09070,"BILIRAKIS, GUS M",H,FL,12.0,REP,INCUMBENT,PO BOX 606,NaN,...,429105.83,306900.57,1306012.36,1260554.41,NaN,NaN,1/1/2015,10/19/2016,N,253347.0
15,15,H4PA18131,"DOYLE, MIKE",H,PA,14.0,DEM,INCUMBENT,205 HAWTHORNE CT,NaN,...,210531.58,291751.36,777713.70,454476.55,NaN,NaN,1/1/2015,10/19/2016,N,252709.0
16,16,H8CO02137,"POLIS, JARED",H,CO,2.0,DEM,INCUMBENT,P.O. BOX 4572,NaN,...,10603.18,91824.88,1281823.94,1102838.77,NaN,NaN,1/1/2015,10/19/2016,N,251988.0
17,17,H6MN05183,"ELLISON, KEITH MAURICE",H,MN,5.0,DEM,INCUMBENT,PO BOX 6072,NaN,...,162747.78,365620.60,2294848.39,1622329.10,NaN,NaN,1/1/2015,10/19/2016,N,249957.0
18,18,H8MO09153,"LUETKEMEYER, W BLAINE",H,MO,3.0,REP,INCUMBENT,215 MAIN STREET,NaN,...,965976.43,1941810.36,1795890.99,550469.87,1050000.00,NaN,1/1/2015,10/19/2016,N,248880.0
19,19,H6IL18088,"LAHOOD, DARIN MCKAY",H,IL,18.0,REP,INCUMBENT,11607 N GLENSHIRE DR,NaN,...,NaN,460882.83,2424378.83,1941921.99,NaN,NaN,1/1/2015,10/19/2016,N,248701.0
20,20,H8FL15107,"POSEY, BILL",H,FL,8.0,REP,INCUMBENT,P. O. BOX 411486,NaN,...,342230.68,588576.15,837793.04,516550.17,NaN,NaN,1/1/2015,10/19/2016,N,246257.0
21,21,H4VA08224,"BEYER, DONALD STERNOFF JR.",H,VA,8.0,DEM,INCUMBENT,1751 POTOMAC GREENS DRIVE,NaN,...,86253.61,814750.02,1982462.14,742454.92,NaN,NaN,1/1/2015,10/19/2016,N,245775.0
22,22,H2MI14111,"LAWRENCE, BRENDA LULENAR",H,MI,14.0,DEM,INCUMBENT,20580 WAYLAND ST,NaN,...,89131.21,228308.15,766433.08,498853.15,NaN,NaN,1/1/2015,10/19/2016,N,244220.0
23,23,H0OH12062,"TIBERI, PATRICK J.",H,OH,12.0,REP,INCUMBENT,6830 MAHOGANY DRIVE,NaN,...,2501982.76,5201935.66,4258847.29,1318584.81,NaN,NaN,1/1/2015,10/19/2016,N,243970.0
24,24,H0LA01087,"SCALISE, STEVE MR.",H,LA,1.0,REP,INCUMBENT,234 JEFFERSON HEIGHTS AVE,NaN,...,482793.91,455004.90,863953.07,2449513.59,NaN,NaN,1/1/2015,10/19/2016,N,243575.0
25,25,H6GA05217,"LEWIS, JOHN R.",H,GA,5.0,DEM,INCUMBENT,2015 WALLACE RD.,NaN,...,184419.65,236216.43,980363.33,655566.55,NaN,NaN,1/1/2015,10/19/2016,N,241773.0
26,26,H4CO04090,"BUCK, KENNETH R",H,CO,4.0,REP,INCUMBENT,PO BOX 338018,NaN,...,140466.09,401585.47,808161.67,550056.91,NaN,NaN,1/1/2015,10/19/2016,N,241424.0
27,27,H4AL06098,"PALMER, GARY",H,AL,6.0,REP,INCUMBENT,1919 OXMOOR RD #235,NaN,...,189712.50,781799.96,1175074.52,451946.24,NaN,NaN,1/1/2015,10/19/2016,N,240897.0
28,28,H8OH05036,"LATTA, ROBERT EDWARD MR",H,OH,5.0,REP,INCUMBENT,1528 MUIRFIELD DRIVE,NaN,...,492878.98,879548.37,998358.48,384494.66,NaN,NaN,1/1/2015,10/19/2016,N,240036.0
29,29,H6FL19087,"ROONEY, FRANCIS",H,FL,19.0,REP,OPEN,610 S. BOULEVARD,NaN,...,NaN,281520.97,4550062.50,4718541.53,450000.00,NaN,4/1/2016,10/19/2016,N,238975.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1784,1784,H6MS01180,"MILLS, MICHAEL P. JR",H,MS,1.0,REP,OPEN,100 A WEST MAIN STREET,NaN,...,NaN,NaN,101100.00,178100.00,NaN,NaN,1/1/2015,9/30/2015,N,NaN
1785,1785,H6MS01172,"PIRKLE, GREGORY D.",H,MS,1.0,REP,OPEN,P.O. BOX 7154,NaN,...,NaN,NaN,212756.00,459834.76,NaN,NaN,1/1/2015,9/30/2015,N,NaN
1786,1786,H6CA46124,"SANCHEZ, HEBERTO M",H,CA,46.0,DEM,OPEN,81 RAINBOW RIDGE,NaN,...,NaN,NaN,3111.94,3111.94,NaN,NaN,6/10/2015,9/30/2015,N,NaN
1787,1787,P60013968,"STEF, MEL",P,US,0.0,IND,OPEN,1119 WHITE STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7/1/2015,9/30/2015,N,NaN
1788,1788,P60007143,"ZUTLER, DANIEL PAUL MR",P,US,0.0,IND,OPEN,7300 SEA GRAPE AVE,NaN,...,NaN,950.00,4000.00,2200.00,NaN,NaN,4/28/2015,9/30/2015,N,NaN
1789,1789,P60002458,"JEWELL, ROGER HENRY",P,US,0.0,NNE,OPEN,316 N AVENUE A #82,NaN,...,11.00,1.00,NaN,NaN,4325.00,NaN,1/1/2015,8/30/2015,N,NaN
1790,1790,P60006731,"MILLER, RAYMOND MELVIN",P,US,0.0,REP,OPEN,325 S BLUE HERON,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4/8/2015,7/15/2015,N,NaN
1791,1791,P60008364,"VEGA, ISAAC ADAM MR.",P,US,0.0,W,OPEN,18116 9TH ST.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6/25/2015,7/15/2015,N,NaN
1792,1792,P00004275,"BROWN, HARLEY D",P,US,0.0,NNE,OPEN,6086 HAPPY LANE,NaN,...,754.92,1918.42,10487.10,9655.02,NaN,NaN,1/1/2015,7/8/2015,N,NaN
1793,1793,H6NY11182,"LANE, JAMES",H,NY,11.0,GRE,OPEN,269 12TH STREET,NaN,...,NaN,257.89,14241.00,13356.89,NaN,NaN,1/1/2015,7/7/2015,N,NaN
1794,1794,H6MS01164,"COLLINS, NANCY",H,MS,1.0,REP,OPEN,1604 BRIAR RIDGE RD,NaN,...,NaN,NaN,102538.35,247121.35,NaN,NaN,1/1/2015,7/1/2015,N,NaN
1795,1795,S6CA00618,"ALBERTSON, STEWART",S,CA,0.0,DEM,OPEN,555 TWIN DOLPHIN DRIVE SUITE 130,NaN,...,NaN,NaN,15250.00,15221.00,1098.00,NaN,1/1/2015,6/30/2015,N,NaN
1796,1796,P60008125,"CORNELL, PHILIP MR.",P,US,0.0,IND,OPEN,1502 15TH AVE SW,NaN,...,50.00,50.00,NaN,NaN,NaN,NaN,4/1/2015,6/30/2015,N,NaN
1797,1797,P60007903,"CULLISON, BROOKS ANDREWS",P,US,0.0,REP,OPEN,235 W CHESTNUT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6/9/2015,6/30/2015,N,NaN
1798,1798,P20002838,"HILL, CHRISTOPHER V",P,US,0.0,REP,OPEN,9900 CORPORATE CAMPUS DR STE 3000,NaN,...,705.00,NaN,NaN,NaN,NaN,NaN,1/1/2015,6/30/2015,N,NaN
1799,1799,P60004900,"JEROBOAN, KINS",P,US,0.0,REP,OPEN,163-49 130TH AVENUE APT GA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1/1/2015,6/30/2015,N,NaN
1800,1800,H6MS01198,"JONES, ROGER STARNER DR.",H,MS,1.0,REP,OPEN,136 NORTH BROOKS STREET,NaN,...,NaN,NaN,140858.00,528638.39,NaN,NaN,1/1/2015,6/30/2015,N,NaN
1801,1801,P60005808,"KAHN, LYNN SANDRA",P,US,0.0,IND,OPEN,PO BOX 497,NaN,...,NaN,619.00,NaN,NaN,NaN,NaN,4/1/2015,6/30/2015,N,NaN
1802,1802,P60005733,"SHO, MUHAMMAD",P,US,0.0,UNK,OPEN,PO BOX 38272,NaN,...,NaN,NaN,NaN,NaN,1.00,NaN,1/1/2015,6/30/2015,N,NaN
1803,1803,P20003158,"STAINFIELD, TAMI L",P,US,0.0,NNE,OPEN,PO BOX 842,NaN,...,4413.35,2977.33,25025.00,22065.98,NaN,NaN,1/1/2015,6/30/2015,N,NaN
1804,1804,P60006814,"LYNCH, DENNIS M",P,US,0.0,REP,OPEN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5/1/2015,6/15/2015,N,NaN
1805,1805,P60006954,"LYNCH, DENNIS MICHAEL",P,US,0.0,REP,OPEN,PO BOX 704,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5/1/2015,6/15/2015,N,NaN
1806,1806,P20003141,"FERGUSON, JOHN GREEN",P,US,0.0,OTH,OPEN,PMB 1704,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7/1/2012,5/31/2015,N,NaN
1807,1807,P60005907,"FLEMING-HODGE, LORI LYNN",P,US,0.0,IND,OPEN,228 HICKS LANE,NaN,...,1000.00,125.00,NaN,NaN,NaN,NaN,3/1/2015,4/30/2015,N,NaN
1808,1808,P60005535,"EMRIT, RONALD SATISH",P,US,0.0,DEM,OPEN,4529 TOWNWALL STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1/1/2015,4/4/2015,N,NaN
1809,1809,P60005931,"BUTTOCKS, SYDNEYS VOLUPTOUS",P,US,0.0,IND,OPEN,143 HIGHLAND AVENUE,NaN,...,5000.00,5000.00,NaN,NaN,NaN,NaN,3/3/2015,3/31/2015,N,NaN
1810,1810,S6CA00568,"MOLNAR, ROBERT",S,CA,0.0,REP,OPEN,PO BOX 321231,NaN,...,1000.00,NaN,1000.00,1000.00,NaN,NaN,1/1/2015,3/31/2015,N,NaN
1811,1811,S6MD03524,"HOLMES, GREGORY",S,MD,0.0,REP,OPEN,13601 MACDERNUT CT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8/29/2017,2/1/2015,N,NaN
1812,1812,H6AS00031,"HUNKIN-FINAU, VAITINASA SALU",H,AS,NaN,DEM,NaN,PO BOX 252 VAILOAUTA,NaN,...,1058.44,4561.00,41670.00,38167.44,NaN,NaN,7/1/2016,10/19/2016,N,NaN
1813,1813,H6AK00235,"LINDBECK, STEVE",H,AK,NaN,DEM,NaN,PO BOX 90025,NaN,...,NaN,64115.92,876316.81,792150.89,13979.83,NaN,4/1/2016,10/19/2016,N,NaN

In [32]:
updated_can_data.to_csv('Resources/renamedCols.csv')

In [10]:
my_list = [4, 8, 1, 4, 8, 3, 9, 11, 200]
numerator = sum(my_list)
denominator = len(my_list)
average_of_list = numerator/denominator
average_of_list

27.555555555555557

In [11]:
def average(my_list):
    numerator = sum(my_list)
    denominator = len(my_list)
    return numerator/denominator

In [13]:
print(average([4, 8, 1, 4, 8, 3, 9, 11, 200]))
print(average([4, 30, 8, 3, 9, 11, 200]))

27.555555555555557
37.857142857142854